language: ruby
sudo: false
cache: bundler
dist: trusty
rvm:
  - 2.2.2
node_js:
  - "node"
services:
  - elasticsearch
before_install:
  - curl -O https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-1.7.3.deb && sudo dpkg -i --force-confnew elasticsearch-1.7.3.deb && sudo service elasticsearch restart
before_script:
  - cp config/example.database.yml config/database.yml
  - psql -c "create database rad_test;" -U postgres
  - bundle exec rake db:migrate
  - npm install
  - npm install -g bower karma-cli
  - bundle exec bowndler update
script:
  - bundle exec rspec
  - npm test
  - bundle exec rubocop -DS
env:
  - SHOW_ETHICAL_AND_SHARIA_FILTER=true SHOW_LANGUAGES_FILTER=true
