language: ruby
sudo: false
cache: bundler
rvm:
  - 2.2.2
services:
  - elasticsearch
before_script:
  - cp config/example.database.yml config/database.yml
  - psql -c "create database rad_test;" -U postgres
  - bundle exec rake db:migrate
  - npm install
  - npm install -g bower karma-cli
  - bundle exec bowndler update
script:
  - bundle exec rspec
  - npm test
  - bundle exec rubocop -DS
